import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `window.op = window.op||function(...args){(window.op.q=window.op.q||[]).push(args);};
          window.op('init', {
            clientId: '3bf872ec-15b8-4308-b0d5-b56e0e15a6f5',
            trackScreenViews: true,
            trackOutgoingLinks: true,
            trackAttributes: true,
          });`,
          }}
        />
        <script src="https://openpanel.dev/op1.js" defer async></script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
